// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Answer: typeof import('./src/components/Answer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Question: typeof import('./src/components/Question.vue')['default']
    Tile: typeof import('./src/components/Tile.vue')['default']
  }
}

export { }
